spring:
  application:
    name: api

  # Configuracao da fonte de dados para MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3307/api_vollmed
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  # Configuracao do Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect